name: Run Object Storage Integration Tests
on:
  push:
  pull_request:
jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        openstack_version: ["stable/zed"]
        php_version: [ 8.1 ]
        ubuntu_version: [20.04]
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with Swift and run objectstorage integration tests with php ${{matrix.php_version}}
    steps:
      - uses: actions/checkout@v2
      - name: get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.php_cs.cache
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-cache-${{ matrix.php_version }}-${{ hashFiles('**.composer.lock') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: curl
          tools: composer:v2
          coverage: none
      - run: composer install --prefer-dist --no-interaction --no-progress
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.11
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            SWIFT_ENABLE_TEMPURLS=True
            SWIFT_TEMPURL_KEY=secretkey
            [[post-config|\$SWIFT_CONFIG_PROXY_SERVER]]
            [filter:versioned_writes]
            allow_object_versioning = true
          enabled_services: 's-account,s-container,s-object,s-proxy'
      - name: execute integration tests
        run: php ./tests/integration/run.php -s=ObjectStore

